// ─── App-wide constants ────────────────────────────────────────────────────
export const OPTION_LETTERS = ['A', 'B', 'C', 'D', 'E'];
export const TIME_LIMIT = 20;
export const ADMIN_EMAILS = [
  'minamuha2020@gmail.com',
  'toph89573@gmail.com',
  'chikibanboni01@gmail.com',
];

// ─── Subjects ──────────────────────────────────────────────────────────────
// Icons are injected in App.jsx after importing IconCode to avoid circular deps
export const SUBJECT_KEYS = [
  { key: 'web',     name: 'Web',  lang: 'KZ' },
  { key: 'java',    name: 'Java', lang: 'KZ' },
  { key: 'web_ru',  name: 'Web',  lang: 'RU' },
  { key: 'java_ru', name: 'Java', lang: 'RU' },
];

// ─── i18n ──────────────────────────────────────────────────────────────────
export const i18n = {
  EN: {
    authSubtitle:    'IT Assessment Platform',
    authDesc:        'Sign in to access technical assessments, track your performance, and compete across Web and Java topics.',
    authBtn:         'Continue with Google',
    authTag:         'Secured · Academic Use Only',
    greeting:        'Welcome back',
    selectAssesment: 'Select Assessment',
    chooseTopic:     'Choose a topic',
    availSubjects:   'Available Subjects',
    reportIssue:     'Report Issue',
    adminPanel:      'Admin Panel',
    profile:         'Profile',
    lang:            'Language',
    theme:           'Theme Color',
    support:         'TG Support',
    signOut:         'Sign Out',
    solvedQ:         'Questions',
    correctQ:        'Correct',
    selectVariant:   'Select Variant',
    variants:        'variants',
    nextQ:           'Next Question →',
    viewResults:     'View Results →',
    retake:          'Retake',
    dashboard:       'Dashboard',
    reviewWrong:     'Review Incorrect Answers',
    flawless:        '// Flawless execution — all answers correct.',
    timeUp:          "Time's up.",
    correct:         'Correct.',
    incorrect:       'Incorrect.',
    grpStats:        'Statistics',
    grpAppearance:   'Appearance',
    grpSystem:       'System & Language',
    mode:            'Display Mode',
    light:           'Light',
    dark:            'Dark',
  },
  RU: {
    authSubtitle:    'Платформа IT-Тестирования',
    authDesc:        'Войдите, чтобы получить доступ к тестам по Web и Java, а также отслеживать свой прогресс.',
    authBtn:         'Войти через Google',
    authTag:         'Безопасно · Только для обучения',
    greeting:        'С возвращением',
    selectAssesment: 'Выбор теста',
    chooseTopic:     'Выберите предмет',
    availSubjects:   'Доступные предметы',
    reportIssue:     'Сообщить об ошибке',
    adminPanel:      'Панель админа',
    profile:         'Настройки Профиля',
    lang:            'Язык',
    theme:           'Цвет темы',
    support:         'Поддержка Telegram',
    signOut:         'Выйти из аккаунта',
    solvedQ:         'Вопросов',
    correctQ:        'Верных',
    selectVariant:   'Выберите вариант',
    variants:        'вариантов',
    nextQ:           'Следующий вопрос →',
    viewResults:     'Результаты →',
    retake:          'Перепройти',
    dashboard:       'В меню',
    reviewWrong:     'Разбор ошибок',
    flawless:        '// Идеальное выполнение — все ответы верны.',
    timeUp:          'Время вышло.',
    correct:         'Верно.',
    incorrect:       'Неверно.',
    grpStats:        'Статистика',
    grpAppearance:   'Оформление',
    grpSystem:       'Система',
    mode:            'Тема оформления',
    light:           'Светлая',
    dark:            'Темная',
  },
  KZ: {
    authSubtitle:    'IT-Тесттеу Платформасы',
    authDesc:        'Web және Java бойынша тесттерге қол жеткізу, прогресті бақылау үшін кіріңіз.',
    authBtn:         'Google арқылы кіру',
    authTag:         'Қауіпсіз · Тек оқу үшін',
    greeting:        'Қайта оралуыңызбен',
    selectAssesment: 'Тестті таңдау',
    chooseTopic:     'Пәнді таңдаңыз',
    availSubjects:   'Қолжетімді пәндер',
    reportIssue:     'Ақаулық туралы хабарлау',
    adminPanel:      'Әкімші панелі',
    profile:         'Профиль параметрлері',
    lang:            'Тіл',
    theme:           'Тақырып түсі',
    support:         'Telegram Қолдау',
    signOut:         'Жүйеден шығу',
    solvedQ:         'Сұрақтар',
    correctQ:        'Дұрыс',
    selectVariant:   'Нұсқаны таңдаңыз',
    variants:        'нұсқа',
    nextQ:           'Келесі сұрақ →',
    viewResults:     'Нәтижелер →',
    retake:          'Қайталау',
    dashboard:       'Мәзірге',
    reviewWrong:     'Қателерді талдау',
    flawless:        '// Керемет нәтиже — барлық жауаптар дұрыс.',
    timeUp:          'Уақыт бітті.',
    correct:         'Дұрыс.',
    incorrect:       'Қате.',
    grpStats:        'Статистика',
    grpAppearance:   'Дизайн',
    grpSystem:       'Жүйе',
    mode:            'Режим',
    light:           'Ашық',
    dark:            'Қараңғы',
  },
};
