// ─── App-wide constants ────────────────────────────────────────────────────
export const OPTION_LETTERS = ['A', 'B', 'C', 'D', 'E'];
export const TIME_LIMIT = 20;
export const MAX_DEVICES = 2;
export const ADMIN_EMAILS = [
  'minamuha2020@gmail.com',
  'toph89573@gmail.com',
  'chikibanboni01@gmail.com',
];

// ─── Contacts ──────────────────────────────────────────────────────────────
export const CONTACT_WHATSAPP = '77775622108'; // Замените на реальный номер без +
export const CONTACT_TELEGRAM = 'f1ower_boy'; // Замените на реальный юзернейм без @


// ─── Subjects ──────────────────────────────────────────────────────────────
// Icons are injected in App.jsx after importing IconCode to avoid circular deps
export const SUBJECT_KEYS = [
  { key: 'web', name: 'Web', lang: 'KZ' },
  { key: 'java', name: 'Java', lang: 'KZ' },
  { key: 'web_ru', name: 'Web', lang: 'RU' },
  { key: 'java_ru', name: 'Java', lang: 'RU' },
];

// ─── i18n ──────────────────────────────────────────────────────────────────
export const i18n = {
  EN: {
    authSubtitle: 'IT Assessment Platform',
    authDesc: 'Sign in to access technical assessments, track your performance, and compete across Web and Java topics.',
    authBtn: 'Continue with Google',
    authTag: 'Secured · Academic Use Only',
    greeting: 'Welcome back',
    selectAssesment: 'Select Assessment',
    chooseTopic: 'Choose a topic',
    availSubjects: 'Available Subjects',
    reportIssue: 'Report Issue',
    adminPanel: 'Admin Panel',
    profile: 'Profile',
    lang: 'Language',
    theme: 'Theme Color',
    support: 'TG Support',
    signOut: 'Sign Out',
    solvedQ: 'Questions',
    correctQ: 'Correct',
    selectVariant: 'Select Variant',
    variants: 'variants',
    nextQ: 'Next Question →',
    viewResults: 'View Results →',
    retake: 'Retake',
    dashboard: 'Dashboard',
    reviewWrong: 'Review Incorrect Answers',
    flawless: '// Flawless execution — all answers correct.',
    timeUp: "Time's up.",
    correct: '',
    incorrect: '',
    grpStats: 'Statistics',
    grpAppearance: 'Appearance',
    grpSystem: 'System & Language',
    mode: 'Display Mode',
    light: 'Light',
    dark: 'Dark',
    purchaseTitle: 'Access Required',
    purchaseDesc: 'To continue taking tests, you need to purchase full access.',
    priceLabel: 'Price:',
    priceValue: '800 ₸',
    contactUs: 'Contact us to activate your account:',
    buyWhatsApp: 'Buy via WhatsApp',
    buyTelegram: 'Buy via Telegram',
    purchaseMessage: 'Hello, I would like to buy access to the website.\nMy login: ',
    deviceBlockedTitle: 'Device Not Registered',
    deviceBlockedDesc: 'This device is not registered for your account. You can have up to 2 registered devices. Contact support to reset your devices.',
    grpDevices: 'Registered Devices',
    deviceLabel: 'Device',
    deviceThis: 'This device',
    deviceRegisteredAt: 'Registered',
    deviceMaxReached: 'Device Limit Reached',
    deviceMaxDesc: 'Maximum 2 devices allowed. Contact support to reset.',
    reportModalTitle: 'Report Issue',
    reportPlaceholder: 'Describe the issue in detail...',
    cancel: 'Cancel',
    submit: 'Submit',
    reportSuccess: 'Report sent successfully!',
    reportError: 'Failed to send report.',
  },
  RU: {
    authSubtitle: 'Платформа IT-Тестирования',
    authDesc: 'Войдите, чтобы получить доступ к тестам по Web и Java, а также отслеживать свой прогресс.',
    authBtn: 'Войти через Google',
    authTag: 'Безопасно · Только для обучения',
    greeting: 'С возвращением',
    selectAssesment: 'Выбор теста',
    chooseTopic: 'Выберите предмет',
    availSubjects: 'Доступные предметы',
    reportIssue: 'Сообщить об ошибке',
    adminPanel: 'Панель админа',
    profile: 'Настройки Профиля',
    lang: 'Язык',
    theme: 'Цвет темы',
    support: 'Поддержка Telegram',
    signOut: 'Выйти из аккаунта',
    solvedQ: 'Вопросов',
    correctQ: 'Верных',
    selectVariant: 'Выберите вариант',
    variants: 'вариантов',
    nextQ: 'Следующий вопрос →',
    viewResults: 'Результаты →',
    retake: 'Перепройти',
    dashboard: 'В меню',
    reviewWrong: 'Разбор ошибок',
    flawless: '// Идеальное выполнение — все ответы верны.',
    timeUp: 'Время вышло.',
    correct: '',
    incorrect: '',
    grpStats: 'Статистика',
    grpAppearance: 'Оформление',
    grpSystem: 'Система',
    mode: 'Тема оформления',
    light: 'Светлая',
    dark: 'Темная',
    purchaseTitle: 'Требуется доступ',
    purchaseDesc: 'Для прохождения тестов необходимо приобрести полный доступ.',
    priceLabel: 'Цена:',
    priceValue: '800 ₸',
    contactUs: 'Свяжитесь с нами для активации аккаунта:',
    buyWhatsApp: 'Купить через WhatsApp',
    buyTelegram: 'Купить через Telegram',
    purchaseMessage: 'Здравствуйте, я хотел(а) купить доступ к сайту.\nМой логин: ',
    deviceBlockedTitle: 'Устройство не зарегистрировано',
    deviceBlockedDesc: 'Это устройство не привязано к вашему аккаунту. Максимум 2 устройства. Свяжитесь с поддержкой для сброса.',
    grpDevices: 'Зарегистрированные устройства',
    deviceLabel: 'Устройство',
    deviceThis: 'Это устройство',
    deviceRegisteredAt: 'Зарегистрировано',
    deviceMaxReached: 'Лимит устройств',
    deviceMaxDesc: 'Максимум 2 устройства. Обратитесь в поддержку.',
    reportModalTitle: 'Сообщить об ошибке',
    reportPlaceholder: 'Подробно опишите проблему...',
    cancel: 'Отмена',
    submit: 'Отправить',
    reportSuccess: 'Сообщение отправлено!',
    reportError: 'Ошибка при отправке.',
  },
  KZ: {
    authSubtitle: 'IT-Тесттеу Платформасы',
    authDesc: 'Web және Java бойынша тесттерге қол жеткізу, прогресті бақылау үшін кіріңіз.',
    authBtn: 'Google арқылы кіру',
    authTag: 'Қауіпсіз · Тек оқу үшін',
    greeting: 'Қайта оралуыңызбен',
    selectAssesment: 'Тестті таңдау',
    chooseTopic: 'Пәнді таңдаңыз',
    availSubjects: 'Қолжетімді пәндер',
    reportIssue: 'Ақаулық туралы хабарлау',
    adminPanel: 'Әкімші панелі',
    profile: 'Профиль параметрлері',
    lang: 'Тіл',
    theme: 'Тақырып түсі',
    support: 'Telegram Қолдау',
    signOut: 'Жүйеден шығу',
    solvedQ: 'Сұрақтар',
    correctQ: 'Дұрыс',
    selectVariant: 'Нұсқаны таңдаңыз',
    variants: 'нұсқа',
    nextQ: 'Келесі сұрақ →',
    viewResults: 'Нәтижелер →',
    retake: 'Қайталау',
    dashboard: 'Мәзірге',
    reviewWrong: 'Қателерді талдау',
    flawless: '// Керемет нәтиже — барлық жауаптар дұрыс.',
    timeUp: 'Уақыт бітті.',
    correct: '',
    incorrect: '',
    grpStats: 'Статистика',
    grpAppearance: 'Дизайн',
    grpSystem: 'Жүйе',
    mode: 'Режим',
    light: 'Ашық',
    dark: 'Қараңғы',
    purchaseTitle: 'Рұқсат қажет',
    purchaseDesc: 'Тесттерді жалғастыру үшін толық рұқсат сатып алу қажет.',
    priceLabel: 'Бағасы:',
    priceValue: '800 ₸',
    contactUs: 'Аккаунтты іске қосу үшін бізбен байланысыңыз:',
    buyWhatsApp: 'WhatsApp арқылы алу',
    buyTelegram: 'Telegram арқылы алу',
    purchaseMessage: 'Сәлеметсіз бе, мен сайтқа кіруге рұқсат сатып алғым келеді.\nМенің логинім: ',
    deviceBlockedTitle: 'Құрылғы тіркелмеген',
    deviceBlockedDesc: 'Бұл құрылғы аккаунтыңызға байланбаған. Ең көбі 2 құрылғы. Сброс үшін қолдаумен байланысыңыз.',
    grpDevices: 'Тіркелген құрылғылар',
    deviceLabel: 'Құрылғы',
    deviceThis: 'Осы құрылғы',
    deviceRegisteredAt: 'Тіркелді',
    deviceMaxReached: 'Құрылғы шегі',
    deviceMaxDesc: 'Ең көбі 2 құрылғы. Қолдаумен байланысыңыз.',
    reportModalTitle: 'Ақаулық туралы хабарлау',
    reportPlaceholder: 'Мәселені толық сипаттаңыз...',
    cancel: 'Болдырмау',
    submit: 'Жіберу',
    reportSuccess: 'Хабарлама жіберілді!',
    reportError: 'Жіберу қатесі.',
  },
};
